apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-book-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-book-store
  template:
    metadata:
      labels:
        app: online-book-store
    spec:
      containers:
      - name: online-book-store
        image: saharsh121/online-book-store:latest
        ports:
        - containerPort: 3000
